### PR TITLE
Add decimal to binary conversion function

### PR DESCRIPTION
**Pull request by ydvmudit07**
**_Closes  #173_** 

### _This pull request adds a function to convert a decimal number to a binary string representation._

_**Changes made:**_

- Added decimalToBinary() function
- Validates decimal number input
- Uses bitwise operator and shifting to efficiently convert decimal to binary
- Tracks remainders and builds binary string
- Handles negative numbers using two's complement
- Returns binary string

_This function will allow easy conversion from decimal to binary in the codebase. I've tested it with various input cases including edge cases._

_**Please review the implementation in Playing with bits/decimalToBinary.cpp and let me know if any changes are required. Also open to suggestions to further improve the code and optimize the conversion approach. Looking forward to getting this pull request merged.**_

-----------------------------------------------------------------------------------------------------------------------------------------

image

### CODE REVIEW

**Comment by ydvmudit07** [comment]
_Kindly review and merge the pull request._ :) @usmanbvp

**Comment by ydvmudit07** [comment]
@usmanbvp

**Comment by ydvmudit07** [comment]
@usmanbvp, **_kindly let me know if there's any issue with the PR, I'll rectify it._**

**Comment by usmanbvp** [comment]
@ydvmudit07   Repo structure has been updated so make sure to adjust your code files in respective folders

**Comment by ydvmudit07** [comment]
@usmanbvp, _I have updated my fork to the latest from the upstream repository. My pull request contains the code changes in the appropriate files and directories matching the project structure, with no conflicts._

_Please review the pull request and let me know if you would like me to make any additional changes to the code or if anything else needs to be modified in the pull request. I am happy to update it based on your feedback._

**Comment by ydvmudit07** [comment]
@usmanbvp , _kindly review and merge if no changes required!_ :)

**Comment by ydvmudit07** [comment]
@usmanbvp, **_based on the existing folder structure of the C++ DSA repository, I just added the decimal to binary conversion code in the "Mathematics" folder._**

_The decimal to binary conversion primarily involves mathematical operations like division and tracking remainders. Since it is more of a mathematical algorithm, the "Mathematics" folder seems like the most relevant place to put it._

**_Let me know if you have any additional context to consider! The overall folder structure looks well organized for a C++ DSA repository._**

**Pull request merged**
