### PR TITLE
file naming format updated

### PR DESCRIPTION
**Pull request by utkarsh-009**
- Format of Folder Naming Updated to make it look in sorted order.

### CODE REVIEW

**Comment by usmanbvp** [comment]
@utkarsh-009  apply the format to all folders.

**Comment by utkarsh-009** [comment]
> @utkarsh-009 apply the format to all folders.

Hey the above formating is applied to all folders already (00 - 99). Please check it again.

**Comment by utkarsh-009** [comment]
Do you want me to use the same formating for files too?

**Comment by usmanbvp** [comment]
@utkarsh-009  you applied the name format upto 9 . I want the format for all the remaining folders.

**Comment by utkarsh-009** [comment]
> @utkarsh-009 you applied the name format upto 9 . I want the format for all the remaining folders.

Hey I don't think there is need to apply for other folders as they are already following the order.
(00 - 99) formatting allows 100 folders to remain in ordered format. The above formatting can be used without any problem for 100 folders.
 
You can check here:
https://github.com/utkarsh-009/DSAProblemsHub

**Pull request merged**
