### PR TITLE
Network problem DFS

### PR DESCRIPTION
**Pull request by Transyltooniaa**
Following is a problem of DFS....  I would rate it as medium .  The approach here is to use Dijkstra'a shortest path algorithm or the bellman for algorithm . So if you know any of these two , then you are good to go. 

A solution is also attached for your reference.

Happy coding

### CODE REVIEW

**Comment by Transyltooniaa** [comment]
Issue #5

**Comment by usmanbvp** [comment]
@Transyltooniaa   Add problems under appropriate folder

**Comment by Transyltooniaa** [comment]
Sorry , I don't know how I uploaded it in BFS.... but now I have fixed it

**Comment by usmanbvp** [comment]
@Transyltooniaa 
you solved network delay problem in two approaches 
1. Dijkstra's Algorithm
2. Bellman Ford Algorithm
so spilt the problem into two files and add them under their folders. 
in every file wrtie the problem statement and then add the code.

Happy coding!

**Comment by Transyltooniaa** [comment]
please check and upadated... original file is now spilt into two files containing solution and question for each

**Comment by usmanbvp** [comment]
@Transyltooniaa   add the splitted solutions under dijkstra's algo and another one under bellman ford alog...observe the repo before addinf the problems.

**Comment by usmanbvp** [comment]
@Transyltooniaa  ok

**Pull request closed without merging**
