### PR TITLE
[Added] Added Problems Of Binary Search Tree(BST).

### PR DESCRIPTION
**Pull request by rohandol112**
**Checklist**
         1. Added Problems Of Binary Search Trees
         
**Current Status**
           -Problems Added In Binary Search Tree (BST) Folder.

### CODE REVIEW

**Comment by rohandol112** [comment]
Added/Pulled with no conflicts.

**Comment by usmanbvp** [comment]
@rohandol112  Add problems in appropriate folder

**Comment by rohandol112** [comment]
yes,they added in Binary Search Trees Folder numbered as 7

**Comment by rohandol112** [comment]
Added Kruskals Algorithm on issue no. #51

**Comment by rohandol112** [comment]
Can you suggest me wht i've to do.actually i'm newbie? so it will get merge

**Comment by usmanbvp** [comment]
@rohandol112  Do some contributions with value so that you can easily get merged your PR's

**Comment by rohandol112** [comment]
you mean i have to give some test cases in my code?

**Comment by rohandol112** [comment]
@usmanbvp please tell me what i've to add please help?

**Comment by rohandol112** [comment]
hello @usmanbvp can you please guide?

**Pull request closed without merging**
