### PR TITLE
[Fixes #41] Added stack related problems

### LINKED ISSUE #41: Stack problems
I would like to add stacks related problems.

#### Please assign this to me.

### PR DESCRIPTION
**Pull request by ritik48**
This pr fixes #41 
@usmanbvp please review this pr

### CODE REVIEW

**Comment by usmanbvp** [comment]
@ritik48   Add comments

**Comment by ritik48** [comment]
hey @usmanbvp , please review this pr again.

**Comment by ritik48** [comment]
@usmanbvp please add hactoberfest-accepted label to this pr.

**Comment by ritik48** [comment]
@usmanbvp please add `hactoberfest-accepted` label to this pr, so this will be counted as my hactoberfest contribution

**Pull request merged**
