### PR TITLE
Euclidean_Algorithm.py

### PR DESCRIPTION
**Pull request by Chandu2000**
Euclidean Algorithm

### CODE REVIEW

**Comment by usmanbvp** [comment]
@Chandu2000 Create a seperate folder named Mathematics under that folder add Euclidean Algorithm

**Review by Chandu2000 — COMMENTED** [review]
Check now

**Comment by Chandu2000** [comment]
Please check now.

**Comment by Chandu2000** [comment]
Please check once again. I sent another pull request.

**Pull request merged**
