### PR TITLE
palindrome checker problem in Linked List using java

### PR DESCRIPTION
**Pull request by sanchitaa14**
Used java to writa a code in VS code based on the Checking if the given text is a palindrome or not.

### CODE REVIEW

**Comment by usmanbvp** [comment]
@sanchitaa14  This problem is already there in Linked List folder. Choose another problem

**Comment by sanchitaa14** [comment]
there was no problem to check whether the linkedlist is a palindrome or not?

**Comment by usmanbvp** [comment]
@sanchitaa14  remove .vscode folder from your recent PR.

the problem palindrome checker is there in linked list folder named as palindromelinkedlist.

**Comment by sanchitaa14** [comment]
Sorry I didn't quite understand your first statement, this is my first hacktoberfest so pardon me for my mistakes.

**Comment by usmanbvp** [comment]
@sanchitaa14  with your problems you had uploaded .vscode named folder into repo. so kindly remove that folder and create a pull request.

**Pull request closed without merging**
